### ISSUE TITLE
Provide version API

### ISSUE THREAD

**Issue by palmerj** [linz/postgresql-dbpatch#17]
Now that the software can be installed without an PG extension, I suggest that a SQL version API is added much like [tableversion](https://github.com/linz/postgresql-tableversion/blob/master/sql/20-version.sql.in).

**Comment by strk** [comment]
This module has only 2 symbols exposed: "apply_patch" (function) and "applied_patches" (table). They already lack a common prefix, other than the schema they are installed in, which is not known in advance. Should the version function also follow this layout ? It'd then be: @extschema@.dbpatch_version() ?

**Comment by strk** [comment]
Well, PR is ready, easier to review: #18
