### ISSUE TITLE
Debian packaging of version 1.2.0

### ISSUE THREAD

**Issue by strk** [linz/postgresql-dbpatch#20]
Just tagged: https://github.com/linz/postgresql-dbpatch/releases/tag/1.2.0

**Comment by strk** [comment]
Ideally we'd want 2 different packages here:
  - postgresql-xx-dbpatch
  - dbpatch
The first would be the extension files (for `CREATE EXTENSION`) while the second would be the extension-less SQL scripts and the dbpatch-loader script.

See also https://github.com/linz/linz_bde_uploader/issues/141
and https://github.com/linz/postgresql-tableversion/issues/65

**Comment by imincik** [comment]
@strk ,  I have no resources do split packaging in to 2 packages now. Is it OK to continue with what we have now ?

**Comment by imincik** [comment]
We can have another task for splitting package and do it later.

**Comment by strk** [comment]
> @strk ,  I have no resources do split packaging in to 2 packages now. Is it OK to continue with what we have now ?

Yes, no problem with that, other than "bde-processor" VM will also
have a running PostgreSQL server (unneeded).

**Comment by imincik** [comment]
What I can do now easily is to drop binary package dependency on PostgreSQL. This will solve the problem of having not necessary running PostgreSQL.

**Comment by strk** [comment]
Sure, why not, thank you.

**Comment by imincik** [comment]
Packages built and uploaded to Launchpad and Packagecloud test branches

**Comment by imincik** [comment]
Packages uploaded to Launchpad prod and pub and to Packagecloud prod as well.
