### ISSUE TITLE
Publish 1.3.0 release on PGXN

### ISSUE THREAD

**Issue by strk** [linz/postgresql-dbpatch#21]
Do we want this @imincik ? There's no mention of PGXN in the README file here so not sure we care.
What do you think @palmerj ?

**Comment by palmerj** [comment]
Don't know really. How many downloads has it had?

**Comment by strk** [comment]
> Don't know really. How many downloads has it had?

I can't find that information from the manager GUI

**Comment by palmerj** [comment]
Hmm. I guess we should find out from admins. If not used then delete. I know table version is used.

**Comment by strk** [comment]
For the record, I asked pgxn admins and they filed an enhancement ticket to make the count available:
https://github.com/pgxn/pgxn-api/issues/27
( could be a fun project :)

**Comment by palmerj** [comment]
@strk is this now done?

**Comment by strk** [comment]
Nope, latest release on PGXN is 1.0.0
I'm still unsure it is worth to publish dbpatch on there, anyway if it is please review PR #29 to help with that, and we could directly upload 1.3.0 when done...

**Comment by strk** [comment]
1.3.0 uploaded to PGXN: https://manager.pgxn.org/distributions/dbpatch/1.3.0
