### ISSUE TITLE
Provide PostgreSQL-agnostic debian package

### ISSUE THREAD

**Issue by strk** [linz/postgresql-dbpatch#24]
The `postgresql-<VERSION>-dbpatch` package contains both the extension and the loader and the loader template. Instead it would be useful to have a the extension agnostic parts be in a separate package `dbpatch` for other packages to rely upon.

**Comment by strk** [comment]
As of current master branch (4f8b2de64c2c240fb59b7f84676bcd84d888cabf) the loader and template files are installed outside of PostgreSQL package directory and do not depend on PostgreSQL package at all, so it should now be possible to create two separate packages: one for the PostgreSQL extension and another for the client-only side (loader, which only depends on `psql` to load the template script)

This hopefully fixes the PostgreSQL version runtime dependency (we don't want runtime dependency on server nor on a specific version)

**Comment by imincik** [comment]
Great, thanks @strk , I will have a look when time will allow

**Comment by strk** [comment]
I'm confused, Travis fails because:
> pg_buildext: error: No current PostgreSQL versions are supported by this package

But the same PostgreSQL version is tested in Travis for Tableversion and it works there ?!

**Comment by strk** [comment]
Figured, debian/pgversions was changed to drop 9.3, I added it back
