### ISSUE TITLE
Publish Debian packages for PostgreSQL 10/11

### ISSUE THREAD

**Issue by strk** [linz/postgresql-dbpatch#41]
Should be possible after merging #40 

Even better would be starting to provide postgresql-agnostic packages too (see #24)

**Comment by imincik** [comment]
Packages for PostgreSQL 10 and 11 are already published. See: https://packagecloud.io/linz/test/packages/ubuntu/trusty/postgresql-11-dbpatch_1.4.0-1linz~trusty1_all.deb

**Comment by strk** [comment]
Thanks @imincik, now we need [packages for tableversion(https://github.com/linz/postgresql-tableversion/issues/165) to  unlock https://github.com/linz/bde-processor-deployment/pull/364
