### ISSUE TITLE
 Publish packages for Ubuntu Bionic distribution

### ISSUE THREAD

**Issue by strk** [linz/postgresql-dbpatch#50]
Tested to work with #49

**Comment by imincik** [comment]
This task is still relevant.

**Comment by imincik** [comment]
This task is still relevant.

**Comment by imincik** [comment]
This task is still relevant.

**Comment by imincik** [comment]
This task is still relevant.

**Comment by strk** [comment]
As I just did package for [linz-bde-uploader](https://github.com/linz/linz-bde-uploader/issues/207) I'm thinking I could try this myself, ok with you @palmerj  ?
Would unblock https://github.com/linz/linz-lds-bde-schema/pull/141

**Comment by strk** [comment]
```
Pushing build-area/postgresql-11-dbpatch_1.5.0-1linz~bionic1_all.deb... success!
Pushing build-area/postgresql-9.4-dbpatch_1.5.0-1linz~bionic1_all.deb... success!
Pushing build-area/postgresql-9.5-dbpatch_1.5.0-1linz~bionic1_all.deb... success!
Pushing build-area/postgresql-9.6-dbpatch_1.5.0-1linz~bionic1_all.deb... success!
Pushing build-area/postgresql-10-dbpatch_1.5.0-1linz~bionic1_all.deb... success!
```

**Comment by strk** [comment]
Reopening until we promote to production

**Comment by imincik** [comment]
@strk , we are promoting packages from `test` repo branch to `prod` after BDE Processor UAT is done (https://github.com/linz/bde-processor-deployment/wiki/Production-Deployment#production-deployment). I think we don't need this ticket. Will close it.
