### ISSUE TITLE
Publish package of version 1.5.0, with dropped PostgreSQL dependency

### ISSUE THREAD

**Issue by imincik** [linz/postgresql-dbpatch#61]
Package new version containing package without PostgreSQL dependency.

**Comment by strk** [comment]
The debian packaging changes did not get in the release-1.5 branch, but the branch does exist already. Meanwhile, the master branch, which got the packaging changes, also got some typo fixes and a README file update. So... what to do here ?

I'm tempted to merge any change from master back into release-1.5 and tag a 1.5.1... from there

**Comment by imincik** [comment]
Packaged and uploaded to `test` branch
