### ISSUE TITLE
Publish new packages for 1.5.0, with the loader fix

### ISSUE THREAD

**Issue by strk** [linz/postgresql-dbpatch#65]
See #64

**Comment by strk** [comment]
@imincik can you please confirm the version of the package you published as mentioned in duplicated issue #66 ( ideally a full version with a link to the actual package ). Thank you !
I'm closing this issue now anyway, to signal other tickets they are now unblocked.

**Comment by imincik** [comment]
@strk , following versions are now in `test`:

* https://packagecloud.io/linz/test/packages/ubuntu/bionic/dbpatch_1.5.0-3linz~bionic1_all.deb
*  https://packagecloud.io/linz/test/packages/ubuntu/bionic/postgresql-10-dbpatch_1.5.0-3linz~bionic1_all.deb
