### ISSUE TITLE
Tag a 1.0.2 release

### ISSUE THREAD

**Issue by strk** [linz/postgresql-dbpatch#7]
Fixes in the Makefile would allow building against PostgreSQL 9.5+
See https://travis-ci.org/linz/linz-bde-schema/builds/271614173?utm_source=github_status&utm_medium=notification

Do you agree @imincik  ?

**Comment by strk** [comment]
NOTE: the Makefile fix was in #4

**Comment by strk** [comment]
For now I used a workaround in the travis config for linz-bde-schema (accepting a make install failure for this package) so this became non-urgent (while maybe still worth?)

**Comment by imincik** [comment]
> Do you agree @imincik ?

Yes, thanks

**Comment by strk** [comment]
When done, workaround of the `make install` bug in 1.0.1 should be removed from the Travis configuration of dependent projects.

**Comment by strk** [comment]
I've started work to close 1.0.2 in #9

**Comment by strk** [comment]
On a second thought, I'm thinking we should skip 1.0.2 and do 1.1.0 instead. I'll open issues for what I think needs be done to get there.

**Comment by strk** [comment]
ticket title updated to match 1.1.0 release, and closed appropriately
