### ISSUE TITLE
Debian packaging of version 1.1.0

### ISSUE THREAD

**Issue by strk** [linz/postgresql-dbpatch#8]
Depends on tagging the release 1.1.0 (still not ready)

**Comment by strk** [comment]
@imincik release 1.1.0 is [ready](https://github.com/linz/postgresql-dbpatch/releases/tag/1.1.0)
A [branch](https://github.com/linz/postgresql-dbpatch/tree/release-1.1) was created too, for 1.1

**Comment by strk** [comment]
NOTE: linz_bde_uploader is installing dbpatch from pgxn too, so cannot change it now to drop the workaround, we first need these packages in a public PPA to install them (or change the travis test to install from sources)

**Comment by imincik** [comment]
Debian package uploaded to Launchpad (ppa:linz/test) for build

**Comment by imincik** [comment]
Package was successfully built in PPA test branch `ppa:linz/test`. I want to test it before moving to prod

**Comment by imincik** [comment]
My package tests are showing that current packaging wrong, fires:

* ./usr/share/postgresql/9.3/extension/META.json

can't be included in package. I need to fix it and upload packages again.

**Comment by imincik** [comment]
Fixes `1.1.1` package uploaded to `ppa:linz/test`.

**Comment by imincik** [comment]
Package looks OK, uploading to `ppa:linz/prod`

**Comment by imincik** [comment]
Uploaded to `ppa:linz-pub/pub`
